monitorv2 {
    output = HDMI-A-1
    mode = 3840x2160@60
    position = 0x0
    scale = 1
    bitdepth = 10
    cm = hdr
    sdrbrightness = 1.7
    sdrsaturation = 0.7
}

# --- Настройки для NVIDIA ---
# Это потом проверить, ибо gemini
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = WLR_NO_HARDWARE_CURSORS,1
# Важно для корректной работы HDR WSI в Kodi
env = ENABLE_HDR_WSI,1
# Исправляет баг синхронизации (EGL_BAD_PARAMETER)
env = EGL_EXT_explicit_sync,0

# --- Автозапуск Kodi ---
# нужен ли тут dbus хер знает
# dispatch exit для завершения hyprland при закрытии kodi, в юните стоит перезапуск сервиса
exec-once = dbus-run-session kodi --windowing=wayland --audio-backend=alsa; hyprctl dispatch exit

animations {
    enabled = false
}
